name: Unit Tests

on: push

jobs:
  unit-tests:
    name: Lint and Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.14.2'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install

      - name: Lint
        run: yarn lint

      - name: Build
        run: build:backend

      - name: Setup Database
        run: docker-compose up -d db

      - name: Run Migrations
        run: yarn workspace @gradejs-public/shared migration:run

      - name: Test
        run: yarn test
